name:  wallysprouts
description: A new Flutter application.

 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^1.7.1
  http: ^0.12.1
  liquid_swipe: ^1.5.0
  mailer: ^3.2.1
  toast: ^0.1.5
  curved_navigation_bar: ^0.3.4
  flutter_staggered_grid_view: ^0.3.2
  flutter_icons: ^1.0.0+1
  cupertino_icons: ^0.1.3 #0.1.2
  image_picker: ^0.6.7+12
  image_cropper: ^1.3.1
  photofilters: ^2.0.1
  shared_preferences: ^0.5.12+2 
  photo_manager: ^0.5.8
  permission_handler: ^5.0.1+1
  video_player: ^0.11.1+2
  audioplayers: ^0.16.2
  file_picker: ^1.4.2
  intl: ^0.16.1
  web_socket_channel: ^1.1.0
  flutter_tts: ^1.3.0
  font_awesome_flutter: ^8.2.0
  flutter_svg: ^0.18.0
  animated_floatactionbuttons: ^0.1.0
  flip_card: ^0.4.4
  cloud_firestore:  ^0.14.0+2
  firebase_storage: ^4.0.0
  cached_network_image: ^2.1.0+1
  firebase_messaging: ^6.0.13
  flutter_local_notifications: ^1.4.3
  flutter_app_badger: ^1.1.2
  flutter_widgets: ^0.1.7+1
  photo_view: ^0.10.2 #^0.9.2
  url_launcher: ^5.4.10
  firebase_core : ^0.5.0
  firebase_auth: ^0.18.0+1  #0.14.0+5
  google_sign_in: ^4.5.3 #4.0.7
  carousel_slider: ^2.3.1
  google_fonts: ^1.1.0
  carousel_pro: ^1.0.0
  fluttertoast: ^7.0.2 #3.1.3
  avatar_glow: ^1.2.0
 # file_picker: ^2.0.12
 #flutter_full_pdf_viewer: ^1.0.6
 #carousel_slider: ^2.3.1
 # google_fonts: ^1.1.0
 # carousel_pro: ^1.0.0
 # intl: ^0.16.1
 # font_awesome_flutter: ^8.2.0
 # url_launcher: ^5.1.6
 # save_image: ^1.0.0
 # dio: ^3.0.10
 
dev_dependencies:
  flutter_test:
    sdk: flutter
   



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/
   - assets/teddy_test.flr
   - assets/Spaceman_inner_sahdow(1).flr
   - assets/doaa(2).flr
   - assets/doaflow(1).flr
   - assets/Teddy.flr
   - assets/dtop(6).flr
   - assets/WorldSpin(1).flr
   - assets/like-unlike.flr
   - assets/success-1.flr
   - assets/launching.flr
   - assets/Test2.mp3
   - assets/A.svg
   - assets/
  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Medium.ttf
          weight: 500 
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
